name: Java CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted # Use your self-hosted runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install

  # deploy-production:
  #   runs-on: self-hosted # Use your self-hosted runner
  #   needs: build
  #   if: github.ref == 'refs/heads/feature'
  #   steps:
  #     - name: Deploy to Production
  #       run: echo "Deploying to Production"

  # deploy-development:
  #   runs-on: self-hosted # Use your self-hosted runner
  #   needs: build
  #   if: github.ref == 'refs/heads/developer'
  #   steps:
  #     - name: Deploy to Development
  #       run: echo "Deploying to Development"
